set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set exrc
set nu
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set noswapfile
set fileformat=unix
set undodir=~/.vim/undodir/
set undofile
set nobackup
set incsearch
set termguicolors
set scrolloff=8
set colorcolumn=80
set signcolumn=yes
set completeopt=menuone,noinsert,noselect
set clipboard+=unnamedplus
set spellfile=~/.config/spell/en.utf-8.add
